import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#b8b3a8',
    primaryColorHover: '#a8a398',
    primaryColorPressed: '#9a958a',
    primaryColorSuppl: '#b8b3a8',
    infoColor: '#8a857d',
    infoColorHover: '#9a9590',
    infoColorPressed: '#7a756d',
    infoColorSuppl: '#8a857d',
    successColor: '#7da87d',
    successColorHover: '#8db88d',
    successColorPressed: '#6d986d',
    successColorSuppl: '#7da87d',
    warningColor: '#c9a76e',
    warningColorHover: '#d4b57e',
    warningColorPressed: '#b8965e',
    warningColorSuppl: '#c9a76e',
    errorColor: '#c06050',
    errorColorHover: '#d07060',
    errorColorPressed: '#a05040',
    errorColorSuppl: '#c06050',
    textColorBase: '#3d3a34',
    bodyColor: '#f6f3ed',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    actionColor: '#f0ece5',
    hoverColor: '#e8e2d9',
    borderColor: '#e8e2d9',
    dividerColor: '#e8e2d9',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    fontSizeLarge: '16px',
    fontFamily: "'Noto Sans SC', 'PingFang SC', system-ui, sans-serif",
    fontFamilyMono: "'Courier New', monospace",
  },
  Button: {
    colorPrimary: '#b8b3a8',
    colorHoverPrimary: '#a8a398',
    colorPressedPrimary: '#9a958a',
    borderPrimary: '1px solid #b8b3a8',
    borderHoverPrimary: '1px solid #a8a398',
    borderPressedPrimary: '1px solid #9a958a',
    textColorPrimary: '#ffffff',
    textColorHoverPrimary: '#ffffff',
    textColorPressedPrimary: '#ffffff',
    colorGhostPrimary: 'transparent',
    borderGhostPrimary: '1px solid #b8b3a8',
    textColorGhostPrimary: '#b8b3a8',
    borderGhostHoverPrimary: '1px solid #a8a398',
    textColorGhostHoverPrimary: '#a8a398',
    colorQuaternary: 'transparent',
    textColorQuaternary: '#3d3a34',
    textColorQuaternaryHover: '#b8b3a8',
    fontWeight: '500',
    borderRadius: '6px',
  },
  Input: {
    color: '#ffffff',
    colorFocus: '#ffffff',
    border: '1px solid #e8e2d9',
    borderHover: '1px solid #b8b3a8',
    borderFocus: '1px solid #b8b3a8',
    boxShadowFocus: '0 0 0 2px rgba(184,179,168,0.2)',
    textColor: '#3d3a34',
    placeholderColor: '#a09a92',
    borderRadius: '6px',
  },
  Card: {
    color: '#ffffff',
    borderColor: '#e8e2d9',
    borderRadius: '8px',
    titleTextColor: '#1a1814',
  },
  Tag: {
    borderRadius: '6px',
  },
  Radio: {
    dotColorActive: '#b8b3a8',
    dotColorActiveHover: '#a8a398',
    textColor: '#3d3a34',
  },
  Space: {},
  Message: {
    textColor: '#3d3a34',
  },
}
