import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#2d5a4a',
    primaryColorHover: '#3a7060',
    primaryColorPressed: '#1f4035',
    primaryColorSuppl: '#2d5a4a',
    infoColor: '#5a8a7a',
    infoColorHover: '#6b9b8b',
    infoColorPressed: '#4a7a6a',
    infoColorSuppl: '#5a8a7a',
    successColor: '#4a7c4a',
    successColorHover: '#5a8c5a',
    successColorPressed: '#3a6c3a',
    successColorSuppl: '#4a7c4a',
    warningColor: '#c9a76e',
    warningColorHover: '#d4b57e',
    warningColorPressed: '#b8965e',
    warningColorSuppl: '#c9a76e',
    errorColor: '#b04040',
    errorColorHover: '#c05050',
    errorColorPressed: '#903030',
    errorColorSuppl: '#b04040',
    textColorBase: '#2c2c2c',
    bodyColor: '#f5f0e8',
    cardColor: '#faf6ef',
    modalColor: '#faf6ef',
    popoverColor: '#faf6ef',
    tableColor: '#faf6ef',
    inputColor: '#fdfaf5',
    actionColor: '#f0ebe3',
    hoverColor: '#e8e0d5',
    borderColor: '#d4c5b0',
    dividerColor: '#d4c5b0',
    borderRadius: '4px',
    borderRadiusSmall: '4px',
    fontSizeLarge: '16px',
    fontFamily: "'Noto Serif SC', 'STSong', 'SimSun', serif",
    fontFamilyMono: "'Courier New', monospace",
  },
  Button: {
    colorPrimary: '#2d5a4a',
    colorHoverPrimary: '#3a7060',
    colorPressedPrimary: '#1f4035',
    borderPrimary: '1px solid #2d5a4a',
    borderHoverPrimary: '1px solid #3a7060',
    borderPressedPrimary: '1px solid #1f4035',
    textColorPrimary: '#faf6ef',
    textColorHoverPrimary: '#faf6ef',
    textColorPressedPrimary: '#faf6ef',
    colorGhostPrimary: 'transparent',
    borderGhostPrimary: '1px solid #2d5a4a',
    textColorGhostPrimary: '#2d5a4a',
    borderGhostHoverPrimary: '1px solid #3a7060',
    textColorGhostHoverPrimary: '#3a7060',
    colorQuaternary: 'transparent',
    textColorQuaternary: '#2d5a4a',
    textColorQuaternaryHover: '#3a7060',
    fontWeight: '500',
    borderRadius: '4px',
  },
  Input: {
    color: '#fdfaf5',
    colorFocus: '#fdfaf5',
    border: '1px solid #d4c5b0',
    borderHover: '1px solid #2d5a4a',
    borderFocus: '1px solid #2d5a4a',
    boxShadowFocus: '0 0 0 2px rgba(45, 90, 74, 0.2)',
    textColor: '#2c2c2c',
    placeholderColor: '#a09080',
    borderRadius: '4px',
  },
  Card: {
    color: '#faf6ef',
    borderColor: '#d4c5b0',
    borderRadius: '8px',
    titleTextColor: '#2c2c2c',
  },
  Tag: {
    borderRadius: '4px',
  },
  Radio: {
    dotColorActive: '#2d5a4a',
    dotColorActiveHover: '#3a7060',
    textColor: '#2c2c2c',
  },
  Space: {},
  Message: {
    textColor: '#2c2c2c',
  },
}
